### ISSUE TITLE
java.lang.NoSuchMethodError: cucumber.runtime.RuntimeOptions.cucumberFeatures(Lcucumber/runtime/io/Resourc eLoader;Lcucumber/runner/EventBus;)Ljava/util/List

### ISSUE THREAD

**Issue by ArielYanarico** [mpinardi/cucumber-performance#1]
I had this Exception after Following all steps described in the documentation https://github.com/mpinardi/cucumber-performance/wiki/Running-Cucumber-Perf

Note: I have tried 3 way to run and got the same result

```
Exception in thread "main" java.lang.NoSuchMethodError: cucumber.runtime.RuntimeOptions.cucumberFeatures(Lcucumber/runtime/io/ResourceLoader;Lcucumber/runner/EventBus;)Ljava/util/List;
        at cucumber.api.perf.FeatureBuilder.getFeatures(FeatureBuilder.java:32)
        at cucumber.api.perf.CucumberPerf.<init>(CucumberPerf.java:119)
        at cucumber.api.perf.cli.Main.main(Main.java:7)
        at core.RunCukesTest.main(RunCukesTest.java:36)
```

**Comment by mpinardi** [comment]
Hi Ariel,
Sorry for the very tardy response. But it seems that you did not have cucumber as part of your project. The error is referencing a method that is in the cucumber core jar itself.

**Comment by NirbhayDee** [comment]
Please give the right solution of this problem.

FAILED CONFIGURATION: @BeforeClass setUpClass
java.lang.NoSuchMethodError: cucumber.runtime.Runtime.<init>(Lcucumber/runtime/io/ResourceLoader;Lcucumber/runtime/ClassFinder;Ljava/lang/ClassLoader;Lcucumber/runtime/RuntimeOptions;)V

**Comment by KashyapPooja** [comment]
Please provide solution for this error.

java.lang.NoSuchMethodError: cucumber.runtime.RuntimeOptions.formatter(Ljava/lang/ClassLoader;)Lcucumber/api/formatter/Formatter;
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:64)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:525)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)



RunnerFile:
package RunnerPAckage;

import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

@RunWith(Cucumber.class)
@CucumberOptions(
		features = "/Mavennew_Project/src/main/java/FeaturePAckagenew",
          glue= {"StepDefPAckage"},
          format= {"pretty","html:test-output"},
          dryRun = true,
          monochrome= true,
          strict = true
          )

public class Runner_1 {



POM.XML

<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.5</version>
			<type>pom</type>
			<scope>test</scope>
		</dependency>


		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.5</version>
			<type>pom</type>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>1.2.5</version>
			<type>pom</type>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-jvm</artifactId>
			<version>1.2.5</version>
			<type>pom</type>
		</dependency>


		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-jvm-deps</artifactId>
			<version>1.0.5</version>
			<scope>provided</scope>
		</dependency>


		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>gherkin</artifactId>
			<version>2.12.2</version>
			<scope>provided</scope>
		</dependency>



		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.0.0-alpha-6</version>
		</dependency>





		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13</version>
			<scope>test</scope>
		</dependency>


		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>5.3.0</version>
		</dependency>



		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>gherkin-jvm-deps</artifactId>
			<version>1.0.3</version>
		</dependency>
