### ISSUE TITLE
Hook step does not work

### ISSUE THREAD

**Issue by fadjer** [mpinardi/cucumber-performance#2]
Hi,

Some methods are now unsupported in Cucumber 3 : 

package cucumber.runner;

```
class HookTestStep extends TestStep implements cucumber.api.HookTestStep {
....

    @Override
    @Deprecated
    public String getStepText() {
        throw new UnsupportedOperationException();
    }
}
```
So if you have a Hook in your scenario it does not work, and we get this execption (bu debbugin):
```

java.lang.UnsupportedOperationException
	at cucumber.runner.HookTestStep.getStepText(HookTestStep.java:68)
	at cucumber.api.perf.result.StepResultListener$2.receive(StepResultListener.java:30)
	at cucumber.api.perf.result.StepResultListener$2.receive(StepResultListener.java:1)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.runner.TestStep.run(TestStep.java:38)
	at cucumber.runner.TestCase.run(TestCase.java:41)
	at cucumber.runner.Runner.runPickle(Runner.java:44)
	at cucumber.api.perf.PerfCucumberRunner.runScenario(PerfCucumberRunner.java:169)
	at cucumber.api.perf.PerfCucumberRunner.runCucumber(PerfCucumberRunner.java:155)
	at cucumber.api.perf.PerfCucumberRunner.call(PerfCucumberRunner.java:133)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

Please fix

**Comment by mpinardi-bao** [comment]
Thanks for the heads up.
I have fixed that locally but I will push out a new revision as soon as possible.
